#!/usr/bin/env python3
"""Extract Claude's response from claude-code-action execution file.

This script parses the execution file generated by anthropics/claude-code-action
and extracts the final Claude response containing the translated release information.
"""

import json
import re
import sys
from pathlib import Path


def extract_json_from_text(text: str) -> str | None:
    """Extract JSON array from text.

    Args:
        text: Text containing JSON

    Returns:
        Extracted JSON string or None if not found
    """
    # First, try to extract from markdown code blocks
    markdown_pattern = r"```(?:json)?\s*(\[.+?\])\s*```"
    markdown_matches = re.findall(markdown_pattern, text, re.DOTALL)

    for match in reversed(markdown_matches):
        try:
            # Validate that it's actually valid JSON
            json.loads(match)
            return match
        except json.JSONDecodeError:
            # Invalid JSON, try next match
            continue

    # If no markdown code blocks, try to find raw JSON array
    json_pattern = r"\[\s*\{.*?\}\s*\]"
    matches = re.findall(json_pattern, text, re.DOTALL)

    # Try matches from last to first (most recent response first)
    for match in reversed(matches):
        try:
            # Validate that it's actually valid JSON
            json.loads(match)
            return match
        except json.JSONDecodeError:
            # Invalid JSON, try next match
            continue

    return None


def extract_claude_response(execution_file_path: str) -> str:
    """Extract Claude's final response from execution file.

    Args:
        execution_file_path: Path to execution file

    Returns:
        Extracted JSON string

    Raises:
        ValueError: If execution file cannot be parsed or response not found
    """
    file_path = Path(execution_file_path)

    if not file_path.exists():
        raise ValueError(f"Execution file not found: {execution_file_path}")

    try:
        with open(file_path) as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        raise ValueError(f"Failed to parse execution file as JSON: {e}") from e

    # Try to extract response from various possible structures
    # Attempt 1: Look for 'response' or 'output' field
    if isinstance(data, dict):
        for key in ["response", "output", "result", "content"]:
            if key in data:
                response_text = data[key]
                if isinstance(response_text, str):
                    json_response = extract_json_from_text(response_text)
                    if json_response:
                        return json_response

        # Attempt 2: Look for messages array
        if "messages" in data and isinstance(data["messages"], list):
            # Get the last assistant message
            for msg in reversed(data["messages"]):
                if isinstance(msg, dict) and msg.get("role") == "assistant":
                    content = msg.get("content", "")
                    if isinstance(content, str):
                        json_response = extract_json_from_text(content)
                        if json_response:
                            return json_response

        # Attempt 3: Look for conversation or history
        for key in ["conversation", "history", "transcript"]:
            if key in data and isinstance(data[key], list):
                # Get the last item
                if data[key]:
                    last_item = data[key][-1]
                    if isinstance(last_item, dict):
                        for field in ["content", "text", "message"]:
                            if field in last_item:
                                text = last_item[field]
                                if isinstance(text, str):
                                    json_response = extract_json_from_text(text)
                                    if json_response:
                                        return json_response

    # If we couldn't find JSON in structured fields, search entire file content
    file_content = file_path.read_text()
    json_response = extract_json_from_text(file_content)
    if json_response:
        return json_response

    raise ValueError("Could not find translated JSON in execution file")


def main():
    """Main entry point."""
    if len(sys.argv) != 2:
        print("Usage: extract_claude_response.py <execution_file>", file=sys.stderr)
        sys.exit(1)

    execution_file = sys.argv[1]

    try:
        response = extract_claude_response(execution_file)
        print(response)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
